---
ansible_python_interpreter: /usr/bin/python
colors:
  foreground: "#f9f9f9"
  background: "#272822"
  black: "#000000"
  red: "#e92f2f"
  green: "#0ed839"
  yellow: "#dddd13"
  blue: "#3b48e3"
  magenta: "#f996e2"
  cyan: "#23edda"
  white: "#ababab"
  bright_black: "#343434"
  bright_red: "#e92f2f"
  bright_green: "#0ed839"
  bright_yellow: "#dddd13"
  bright_blue: "#3b48e3"
  bright_magenta: "#f996e2"
  bright_cyan: "#23edda"
  bright_white: "#f9f9f9"
fonts:
  i3: Roboto
  editor: JetBrains Mono
  terminal: JetBrains Mono
  glyphs:
    - PowerlineSymbols
    - Font Awesome 5 Brands
    - Font Awesome 5 Free
    - devicons
    - Material Design Icons Desktop
    - MesloLGS Nerd Font Mono
reflector_country: Germany
