---
- name: Ensure required packages are present
  become: yes
  pacman:
    name:
      - base-devel
      - go

- name: Check if yay is present
  command: which yay
  register: yay_is_present
  changed_when: yay_is_present.rc == 1
  failed_when: yay_is_present.rc >= 2

- name: Ensure yay is present
  block:
    - name: Clone yay repo
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /tmp/yay

    - name: Install yay
      command:
        chdir: /tmp/yay
        cmd: makepkg -Cfis --noconfirm
        creates: /usr/bin/yay

    - name: Remove yay repo
      file:
        path: /tmp/yay
        state: absent
  when: yay_is_present.rc == 1

- name: Ensure aur_builder user is present
  become: yes
  user: name=aur_builder

- name: Ensure aur_builder can run pacman with sudo
  become: yes
  lineinfile:
     path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
     state: present
     line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
     validate: /usr/sbin/visudo -cf %s
     create: yes
