---
- name: Ensure package is present
  become: true
  pacman:
    name: cups
    update_cache: true

- name: Ensure cupsd service is stopped and disabled
  systemd:
    name: org.cups.cupsd.service
    state: stopped
    enabled: no

- name: Ensure cupsd socket is started and enabled
  systemd:
    name: org.cups.cupsd.socket
    state: started
    enabled: yes
