---
- name: Ensure package is present
  become: true
  pacman:
    name:
      - cups
      - cups-pdf

- name: Ensure cups service is stopped and disabled
  become: yes
  systemd:
    name: cups.service
    state: stopped
    enabled: no

- name: Ensure cups socket is started and enabled to only start CUPS when a program wants to use the service
  become: yes
  systemd:
    name: cups.socket
    state: started
    enabled: yes
