---
- hosts: all
  become: true
  pre_tasks:
    - name: Ensure common base packages are present
      pacman:
        name:
          - base-devel
          - gvfs

    - name: Ensure common services are started and enabled
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - fstrim.timer
        - systemd-timesyncd.service

  roles:
    - role: ansible-role-dotfiles
      vars:
        dotfiles_install_packages: true
        dotfiles_zsh_install_external_extensions: false

- hosts: all
  roles:
    - cpu_ucode
    - reflector
    - yay
    - fonts
    - ansible-role-dotfiles
    - xorg
    - lightdm
    - keyring
    - termite
    - i3
    - i3lock
    - i3blocks
    - rofi
    - picom
    - dunst
    - arandr
    - networkmanager
    - pulseaudio
    - blueman
    - gparted
    - galculator
    - gpicview
    - gimp
    - thunar
    - firefox
    - chromium
    - code
    - docker
    - vagrant
    - vlc
    - cups
