---
- hosts: all

  pre_tasks:
    - name: Ensure common packages are present
      become: yes
      pacman:
        name:
          - base-devel
          - git
          - gvfs
          - htop
          - vim

    - name: Ensure common services are started and enabled
      become: yes
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - fstrim.timer
        - systemd-timesyncd.service

  roles:
    - cpu_ucode
    - reflector
    - yay
    - fonts
    - zsh
    - xorg
    - lightdm
    - keyring
    - termite
    - ranger
    - i3
    - i3lock
    - i3blocks
    - rofi
    - picom
    - dunst
    - arandr
    - networkmanager
    - pulseaudio
    - blueman
    - gparted
    - galculator
    - gpicview
    - gimp
    - thunar
    - firefox
    - chromium
    - code
    - docker
    - vagrant
    - vlc
    - cups
