---
- hosts: all
  become: true
  pre_tasks:
    - name: Ensure packages are present
      pacman:
        name:
          - arandr
          #- base-devel
          - blueman
          # - chromium
          - cups
          - cups-pdf
          - dosfstools
          - firefox
          #- gimp
          - gparted
          #- gpicview-gtk3
          - gvfs
          - mtools
          - pavucontrol
          # - pulseaudio
          # - pulseaudio-alsa
          # - pulseaudio-bluetooth
          - thunar
          # - vagrant
          # - virtualbox
          # - virtualbox-host-modules-arch
          - vim
          - vlc

    - name: Ensure services are started and enabled
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - bluetooth.service
        - cups.socket
        - fstrim.timer
        - systemd-timesyncd.service

    - name: Ensure services are stopped and disabled
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - cups.service

  roles:
    - role: reflector
    - role: fonts
    - role: lightdm
    - role: keyring
    - role: networkmanager
    - role: i3lock
    - role: docker
  #   - role: ansible-role-dotfiles
  #     vars:
  #       dotfiles_install_packages: true
  #       dotfiles_zsh_install_external_extensions: false

  # tasks:
  #   - name: Ensure zsh is the default shell
  #     user:
  #       name: "{{ item }}"
  #       shell: /usr/bin/zsh
  #     with_items:
  #       - root
  #       - "{{ arch_user }}"
