---
- name: Ensure packages are present
  become: yes
  pacman:
    name:
      - xorg
      - "{{ xorg_xf86_video }}"
      - xss-lock
    update_cache: yes

- name: Ensure keyboard.conf is present
  become: yes
  copy:
    src: 00-keyboard.conf
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    mode: 0644

- name: Ensures .Xresources.d dir exists
  file:
    path: "{{ ansible_env.HOME }}/.Xresources.d"
    state: directory
    recurse: yes

- name: Ensure colors file is present
  template:
    src: colors
    dest: "{{ ansible_env.HOME }}/.Xresources.d/colors"
    mode: 0644

- name: Ensure colors will be included in .Xresources
  lineinfile:
    path: "{{ ansible_env.HOME }}/.Xresources"
    line: '#include ".Xresources.d/colors"'
    create: yes
    mode: 0644

- name: Ensure .xinitrc is present
  copy:
    src: .xinitrc
    dest: "{{ ansible_env.HOME }}/.xinitrc"
    mode: 0644

- name: Ensure xorg.conf file exists
  become: yes
  template:
    src: xorg.conf
    dest: /etc/X11/xorg.conf
    mode: 0644
