---
- name: Ensure package is present
  become: true
  pacman:
    name: galculator
    update_cache: true

- name: Ensures config dir exists
  file:
    path: "{{ ansible_env.HOME }}/.config/galculator"
    state: directory
    recurse: yes

- name: Ensure config is present
  copy:
    src: galculator.conf
    dest: "{{ ansible_env.HOME }}/.config/galculator/galculator.conf"
    mode: 0644
