---
- name: Ensure package is present
  become: yes
  pacman:
    name: zsh
    update_cache: yes

- name: Ensure oh my zsh is present
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Ensure .zshrc file exists
  template:
    src: .zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0644

- name: Ensure zsh is the default shell
  become: yes
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
