---
- name: Ensure package is present
  become: yes
  pacman:
    name:
      - termite

- name: Ensures config dir exists
  file:
    path: "{{ ansible_env.HOME }}/.config/termite"
    state: directory
    recurse: yes

- name: Ensure config is present
  template:
    src: config
    dest: "{{ ansible_env.HOME }}/.config/termite/config"
    mode: 0644
