---
- name: Ensure package is present
  become: true
  pacman:
    name:
      - reflector
    update_cache: yes

- name: Ensure service file is present
  become: true
  template:
    src: reflector.service
    dest: /etc/systemd/system/reflector.service
    mode: 0644
  notify: reload reflector.service

- name: Ensure timer file is present
  become: true
  copy:
    src: reflector.timer
    dest: /etc/systemd/system/reflector.timer
    mode: 0644
  notify: restart reflector.timer

- name: Ensure timer is enabled
  become: true
  systemd:
    name: reflector.timer
    enabled: yes
