---
- name: Ensure package is present
  become: true
  pacman:
    name:
      - reflector
    update_cache: yes

- name: Ensure hooks directory exists
  become: true
  file:
    name: /etc/pacman.d/hooks
    state: directory
    recurse: yes

- name: Ensure mirrorupgrade.hook file is present
  become: true
  template:
    src: mirrorupgrade.hook
    dest: /etc/pacman.d/hooks/mirrorupgrade.hook
    mode: 0644
