---
- name: Ensure rofi package is present
  become: yes
  pacman:
    name: rofi

- name: Ensures rofi config dir exists
  file:
    path: "{{ ansible_env.HOME }}/.config/rofi"
    state: directory
    recurse: yes

- name: Ensure rofi config file is present
  copy:
    src: config.rasi
    dest: "{{ ansible_env.HOME }}/.config/rofi/config.rasi"
    mode: 0644
