---
- name: Ensure package is present
  become: yes
  pacman:
    name:
      - networkmanager
      - network-manager-applet

- name: Ensure config is present
  become: yes
  copy:
    src: NetworkManager.conf
    dest: /etc/NetworkManager/NetworkManager.conf
    mode: 0644
  notify: restart NetworkManager.service

- name: Ensure service is enabled
  become: yes
  systemd:
    name: NetworkManager
    enabled: yes
